name: Python CI Pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
          
      - name: Create Virtual Environment, Install Dependencies, Lint, and Test
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pylint pytest
          pylint $(git ls-files '*.py')
<<<<<<< HEAD
          pytest
=======
          pytest
>>>>>>> 26734fe5130f21125e73dac80e88e6dd87284c66
